### ISSUE TITLE
training on 5m dataset instead of the original 20m

### ISSUE THREAD

**Issue by Kartikgar** [jac99/MinkLoc3D#5]
Hi,
I have been trying to train Minkloc3D on the oxford dataset preprocessed such that each training submap covers 5m of car trajectory and are 2.5m apart as compared to the original training submaps that cover 20m of car trajectory and are 10m apart. The results which I am getting after 40 epochs is very inferior in comparison to the results published. The model was trained with the default parameters. Another interesting thing was that the embeddings collapsed when I increased the batch size to 32 instead of the default 16.
Any insight to solve this issue is appreciated.

**Comment by jac99** [comment]
Submaps constructed by aggregating 2D LiDAR scans during 5m traversal of the car are rather small. I think 5m is too small for localization/place recognition. This covers only a small part of the building, and there may be many similar parts of the building in different places. Visualize your point clouds, and see if they look good enough for place recognition. I think they are too small and the method will not work.

Did you also change thresholds to generate positive and negative elements? Default thresholds (positive elements are at most 10 meters apart and negative more than 50 meters apart) make sense when point clouds cover 20 meter distance. If point clouds cover 5 meter distance, the positive threshold should be much lower than 5 meter, something like 2.5 meter - so there's sufficient overlap between any two positive examples. Otherwise, the training will collapse.
Also negative threshold should be decreased, to something like 10 meter.

What was the reason to create such small submaps? If you want to increase the precision of the localization - if you want to have better results when evaluating the descriptors with a small threshold (i.e. calculate Recall@k with a small threshold like 5m for true positive), the better option is to:
- construct point clouds, so they cover 20m of car trajectory (as in my paper), only sample them denser, so they are 2.5m meters apart
- decrease positive and negative thresholds - e.g. positive threshold is 5m and the negative threshold is 15 meters (or maybe even small, 10 meters)
The network should learn, that point clouds with large overlap are similar and if the overlap is small or there's not overlap they are dissimilar.

**Comment by jac99** [comment]
Closed due to inactivity
