### ISSUE TITLE
confused about self.inplanes

### ISSUE THREAD

**Issue by dkjshk** [jac99/MinkLoc3D#6]
hello, i research for place recognition and i am very interested in your work. however, i am confused about the value of self.inplanes while building conv2.  i think self.inplanes only change to 64 after building conv2's resnet block . so the first kernel of conv2 is still C32 instead of C64 which is defined
by

self.convs.append(ME.MinkowskiConvolution(self.inplanes, self.inplanes, kernel_size=2, stride=2, dimension=D))

but it still works because of resnet block downsampling.
am i misunderstood?

**Comment by jac99** [comment]
Hi,
yes are 100% right, there's a mistake in the network details in Table 1in the paper "MinkLoc3D: Point Cloud Based Large-Scale Place Recognition". In the paper, the first convolutional layer in Block 2 has the following parameters: 64 filters, with kernel 2 (which means 2x2x2) and stride 2. 
Whereas, in the code the first convolutional layer in Block2 , has only 32 filters with kernel 2 and stride 2. The subsequent residual block takes 32 channel input and outputs 64 channels. This works, because the residual connection includes a "downsample" block (actually the name is quite misleading, it doesn't do any downsampling) which uses 1x1x1 convolution to transform 32 channel input into 64 channels.

**Comment by dkjshk** [comment]
Thank you for your reply, i get what you mean. By the way,  i think this situation may also happens in minkloc3Dv2 by the code you released now.

**Comment by jac99** [comment]
Yes, I'll fix it in the camera-ready version of MinkLoc3Dv2 paper. Thanks for finding this issue and informing me.
