### ISSUE TITLE
Complexity Analysis

### ISSUE THREAD

**Issue by BIT-MJY** [jac99/MinkLoc3D#9]
Hi @jac99 ,

Thanks for your great open-source code! Currently I want to compare our method with MinkLoc3D on FLOPs, but I find it difficult to calculate FLOPs for the MinkowskiEngine model. Have you ever achieved this using some existing tools or your ad-hoc function?

**Comment by jac99** [comment]
Hi, 
unfortunately, I haven't done any FLOPS analysis of MinkLoc3D method. 
I've seen a similar question posted in MinkowskiEngine repo: https://github.com/NVIDIA/MinkowskiEngine/issues/115, but there was no answer. MinkowskiEngine uses some clever hashing method to quickly find values of neighborhood voxels in order to efficiently compute sparse convolutions. So in the best case retrieving voxel values is constant, but in the worst case it is linear with respect to the number of points.
Maybe take a more pragmatic approach, benchmark the methods on the same hardware, and report processing time per point cloud.

**Comment by BIT-MJY** [comment]
Get it. Thanks for your suggestion.
